/**
 * The exception package is used for throwing an exception.
 */
package by.training.task02.exception;
